ddzone/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls'))
]

posts/urls.py
from django.urls import path, include
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.PostListView.as_view(), name='list'),
    path('new/', views.PostCreateView.as_view(), name='create'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='detail'),
]

posts/models.py
from django.db import models


class Post(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class PostImage(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    img = models.FileField(upload_to='public/uploads/')

    def imgName(self):
        return self.img.name[7:]

posts/forms.py
from django.core.validators import FileExtensionValidator
from django import forms

class PostCreateForm(forms.Form):
    title = forms.CharField()

posts/views.py
from django.views.generic.edit import FormView
from django.views.generic import ListView, DetailView
from django.http import HttpResponse
from django.urls import reverse_lazy, reverse
from .forms import PostCreateForm
from .models import Post, PostImage


class PostListView(ListView):
    model = Post

class PostDetailView(DetailView):
    model = Post

class PostCreateView(FormView):
    form_class = PostCreateForm
    template_name = 'posts/create.html'

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)

        if form.is_valid():
            post = Post(name=form.cleaned_data['title'])
            post.save()

            flag = True
            i = 0
            while(flag):
                key = 'file[%d]' % i
                f = request.FILES.get(key)
                if f is not None:
                    img = PostImage(post=post, img=f)
                    img.save()
                    i += 1
                else:
                    flag = False
            return HttpResponse(reverse('posts:detail', args=(post.id,)))
        else:
            return HttpResponse(reverse('posts:create'))

posts/templates/posts/base.html
{% load staticfiles %}

<html>
    <head>    
        <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}" />
        <link rel="stylesheet" href="{% static 'css/dropzone.css' %}">
        <title>Django Dropzone</title>
    </head>
    <body>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                {% block content %}
                {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

posts/templates/posts/create.html
{% extends "posts/base.html" %}
{% load staticfiles %}

{% block content %}
    <h1>Create post</h1>
    <a class="back" href="{% url 'posts:list' %}">Back</a>
    <form id="postCreateForm" enctype="multipart/form-data" method="post" action="{% url 'posts:create' %}">
        {% csrf_token %}
        <p><label>Title: </label><input id="title" type="text" name="title" required/></p>
        <div id="dropzone" class="dropzone"></div>
        <button type="submit">Create</button>
    </form>
    <script src="{% static 'js/dropzone.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends "posts/base.html" %}
{% load static %}

{% block content %}
    <a href="{% url 'posts:list' %}">Back</a>
    <div class="post">
        <h2>{{ post.name }}</h2>
        {% for img in post.postimage_set.all %}
            <img src="{% static img.imgName %}" alt="" />
        {% endfor %}
    </div>
{% endblock %}

posts/templates/posts/post_list.html
{% extends "posts/base.html" %}
{% load static %}

{% block content %}
    <h1>Posts</h1>
    <a href="{% url 'posts:create' %}">Add New</a>
    {% for post in object_list %}
        <h2><a href="{% url 'posts:detail' post.id %}">{{ post.name }}</a></h2>
    {% endfor %}
{% endblock %}